#!/usr/bin/env python3

import json

config_file = '/etc/aros/config.json'

try:
  file = open(config_file, 'r')
except FileNotFoundError:
  print('AROS configuration not found at %s' % (config_file))
  exit(1)

config = json.loads(f.read())

if config['version'] != 1:
  print('Unknown config version: %s' % (config['version']))
