use axum::extract::State;
use axum::Json;
use serde::Serialize;
use std::collections::HashMap;

use crate::ports::DockerPort;
use crate::{AppError, AppState};

#[derive(Debug, Serialize, Clone)]
pub struct AppProxy {
    pub app_id: String,
    pub name: String,
    pub path: String,
    pub target: String,
    pub running: bool,
}

/// List all app web UI proxy routes (for the gateway nginx config)
pub async fn list_proxies(
    State(state): State<AppState>,
) -> Result<Json<Vec<AppProxy>>, AppError> {
    let containers = state.docker.list_containers().await.unwrap_or_default();
    let mut proxies = Vec::new();

    // Map of known apps to their web UI container ports
    let app_web_ports: HashMap<&str, u16> = HashMap::from([
        ("tar1090", 80),
        ("acarshub", 80),
        ("graphs1090", 80),
        ("ais-catcher", 8100),
        ("satdump", 8081),
        ("rtl-airband", 8000),
    ]);

    for container in &containers {
        let name = container.name.trim_start_matches("airwaves-");

        if let Some(&port) = app_web_ports.get(name) {
            proxies.push(AppProxy {
                app_id: name.to_string(),
                name: container.name.clone(),
                path: format!("/apps/{}/", name),
                target: format!("http://{}:{}", container.name, port),
                running: container.state == "running",
            });
        }
    }

    Ok(Json(proxies))
}

/// Generate nginx upstream config for all running app web UIs.
/// The gateway container mounts /etc/airwaves/nginx/ and includes these configs.
pub async fn generate_nginx_config(
    State(state): State<AppState>,
) -> Result<Json<serde_json::Value>, AppError> {
    let containers = state.docker.list_containers().await.unwrap_or_default();

    let app_web_ports: HashMap<&str, u16> = HashMap::from([
        ("tar1090", 80),
        ("acarshub", 80),
        ("graphs1090", 80),
        ("ais-catcher", 8100),
        ("satdump", 8081),
        ("rtl-airband", 8000),
    ]);

    let mut config_lines = Vec::new();
    config_lines.push("# Auto-generated by airwaves-manager - do not edit".to_string());
    config_lines.push(format!("# Generated at {}", chrono::Utc::now().to_rfc3339()));
    config_lines.push(String::new());

    let mut count = 0;
    for container in &containers {
        if container.state != "running" {
            continue;
        }
        let name = container.name.trim_start_matches("airwaves-");

        if let Some(&port) = app_web_ports.get(name) {
            config_lines.push(format!("# App: {}", name));
            config_lines.push(format!("location /apps/{}/ {{", name));
            config_lines.push(format!("    set $app_{} {};", name.replace('-', "_"), container.name));
            config_lines.push(format!("    proxy_pass http://$app_{}:{}/;", name.replace('-', "_"), port));
            config_lines.push("    proxy_set_header Host $host;".to_string());
            config_lines.push("    proxy_set_header X-Real-IP $remote_addr;".to_string());
            config_lines.push("    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;".to_string());
            config_lines.push("    proxy_set_header X-Forwarded-Proto $scheme;".to_string());
            config_lines.push("    proxy_buffering off;".to_string());
            config_lines.push("}".to_string());
            config_lines.push(String::new());
            count += 1;
        }
    }

    let config_content = config_lines.join("\n");

    // Write to shared volume
    let config_path = "/etc/airwaves/nginx/apps.conf";
    if let Some(parent) = std::path::Path::new(config_path).parent() {
        std::fs::create_dir_all(parent).ok();
    }
    std::fs::write(config_path, &config_content)
        .map_err(|e| AppError::Internal(format!("Failed to write nginx config: {}", e)))?;

    // Signal nginx to reload (the gateway container)
    // This works because both containers share the Docker network
    let _ = std::process::Command::new("docker")
        .args(["kill", "--signal=HUP", "airwaves-gateway"])
        .output();

    Ok(Json(serde_json::json!({
        "status": "generated",
        "app_count": count,
        "config_path": config_path,
    })))
}
