#!/bin/bash

THIS_SCRIPT="header"
MOTD_DISABLE=""

[[ -f /etc/armbian-release ]] && . /etc/armbian-release
[[ -f /etc/armbian-distribution-status ]] && . /etc/armbian-distribution-status
[[ -f /etc/os-release && -f /etc/armbian-distribution-status ]] && DISTRIBUTION_CODENAME=$(grep VERSION_CODENAME /etc/os-release | cut -d"=" -f2) && DISTRIBUTION_STATUS=$(grep "$DISTRIBUTION_CODENAME" /etc/armbian-distribution-status | cut -d"=" -f2)
[[ -f /etc/default/armbian-motd ]] && . /etc/default/armbian-motd
[[ -f /etc/airwaves-release ]] && . /etc/airwaves-release

for f in $MOTD_DISABLE; do
	[[ "$f" == "$THIS_SCRIPT" ]] && exit 0
done

KERNELID=$(uname -r)

TERM=linux toilet -f standard -F metal Airwaves OS
echo -e "Welcome to \e[0;91mAirwaves OS v${AIRWAVES_VERSION}\x1B[0m based on \e[0;91mArmbian ${VERSION} ${DISTRIBUTION_CODENAME^}\x1B[0m with \e[0;91mLinux $KERNELID\x1B[0m\n"

if [[ "$IMAGE_TYPE" != "stable" ]]; then
	[[ "$IMAGE_TYPE" == "user-built" ]] && UNSUPPORTED_TEXT="built from source"
	[[ "$IMAGE_TYPE" == "nightly" ]] && UNSUPPORTED_TEXT="nightly build"
fi

if [[ -n "${UNSUPPORTED_TEXT:-}" ]]; then
	echo -e "\e[0;93mNote: \x1B[0m$UNSUPPORTED_TEXT\n"
fi
