org: "airframesio" # can't be an expression, only string.

# armbian/build coordinates
org_and_build_repo: "armbian/build"
build_ref: "v23.05"

# armbian/os coordinates. set all to empty to not use userpatches.
org_and_userpatches_repo: "airframesio/airwaves-os"
userpatches_ref: "main"
userpatches_dir: "armbian/armbian-userpatches" # folder inside the userpatches repo; use "." if stuff is in the root of the repo

ghcr_user: "${{ github.repository_owner }}"
userpatches_config_for_prepare_job: "airwaves-os" # use "" for no config file
