#!/usr/bin/env bash

echo "airwaves-config v0.0.1"
echo "Airwaves OS Configuration for CLI"
echo ""

if [[ $EUID != 0 ]]; then
  echo "This tool requires root privileges. Try again with \"sudo \"!" >&2
  sleep 2
  exit 1
fi

if  [[ -f ${BASH_SOURCE}-functions ]]; then source ${BASH_SOURCE}-functions;
  elif  [[ -f /opt/airwaves-config/functions.sh ]]; then source /opt/airwaves-config/functions.sh;
  else exit 1;
fi

if [[ $1 == "--help" ]]; then
  echo "Commands:"
  echo ""
  echo "  set-hostname HOSTNAME    Sets the system's hostname"
  echo "  set-user-uuid UUID       Sets the Airframes user uuid"
  echo "  set-user-token TOKEN     Sets the Airframes user token"
  echo ""
  echo "  test-auth                Tests if authentication to Airframes is working"
  echo ""
  echo "  apply                    Apply the current Airwaves configuration to the system"
  echo "  show                     Show current configuration"
  echo "  repair                   Repair the system and Airwaves configuration"
  echo "  upgrade                  Upgrade to the latest release of Airwaves"
  echo ""
  exit
fi

. /opt/airwaves/build.config


ApplyConfig() {
  /opt/airwaves/scripts/apply-config
}

ShowConfig() {
  /opt/airwaves/scripts/show-config
}

Repair() {
  /opt/airwaves/scripts/repair
}

Upgrade() {
  /opt/airwaves/scripts/update
}

#main "$@"


while true
do
  LIST=()

  LIST+=( "System" "System settings" )
  LIST+=( "Airframes" "Airframes.io settings" )

  LIST_LENGTH="$((11+${#LIST[@]}/2))"
  BOX_LENGTH=${#LIST[@]}
  MENU_TITLE="Configure Airwaves OS"

  DIALOG_CANCEL=1
  DIALOG_ESC=255
  TITLE_LENGTH=${#MENU_TITLE}

  [[ "$TITLE_LENGTH" -lt 60 ]] && TITLE_LENGTH="60"

  if [[ -z "$1" ]]; then
    exec 3>&1
    main=$(dialog --colors --backtitle "${BACK_TITLE}" --title " aros-config " --clear --cancel-label "Exit" --menu "\n$MENU_TITLE \nWebsite: \Z1https://airframes.io\Z0\n " $LIST_LENGTH $TITLE_LENGTH $BOX_LENGTH "${LIST[@]}")
    exec 3>&-

    exit_status=$?

    [[ $exit_status == $DIALOG_CANCEL || $exit_status == $DIALOG_ESC ]] && exit

    dialog --backtitle "$BACK_TITLE" --title "Please wait" --infobox "\nLoading ${main,,} submodule ... " 5 $((26+${#main}))
  fi

  case $1 in
    "show")
      ShowConfig
      exit 0
      ;;
    "system")
      submenu_system
      ;;
    "airframes")
      submenu_airframes
      ;;
    "armbian")
      armbian-config
      ;;
    "help")
      unset main
      t="airwaves-config is a CLI tool to customize the Airwaves OS."
      show_box "Help" "$t" "18"
      ;;
  esac

done
