display_alert "Include" "common-airwaves" "info"

# Extensions - docker-ce must be enabled before our extensions
enable_extension "docker-ce"
enable_extension "airwaves-base"
enable_extension "airwaves-docker"
enable_extension "airwaves-networking"
enable_extension "airwaves-hardware"

# Base OS settings
declare -g BUILD_MINIMAL="yes"
declare -g BUILD_DESKTOP="no"
declare -g KERNEL_CONFIGURE="no"

# Branding
declare -g VENDOR="Airwaves_OS"
declare -g MAINTAINER="Airframes"
declare -g MAINTAINEREMAIL="maintainer@airframes.io"

# Defaults
declare -g ROOTPWD="airwaves"
declare -g HOST="airwaves"
declare -g DEST_LANG="en_US.UTF-8"

# Build output
declare -g COMPRESS_OUTPUTIMAGE="img,sha,xz"
declare -g EXPERT="yes"
declare -g PROGRESS_LOG_TO_FILE="yes"
declare -g SHOW_DEBUG="no"
declare -g SHOW_COMMANDS="no"

# Feature toggles
declare -g WIREGUARD="no"
declare -g EXTRA_WIFI="yes"
declare -g AUFS="no"
declare -g SYNC_CLOCK="no"

function run_after_build__export_image_version_to_gha() {
    github_actions_add_output "armbian_image_version" "${version}"
}
