name: Build Airwaves OS (Armbian base)

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      set_branch:
        description: "Branch: edge / current / legacy"
        required: false
        default: "current"
      set_release:
        description: "Release: jammy / focal / bullseye"
        required: false
        default: "jammy"
      set_board:
        description: "Board: odroidn2 / lepotato"
        required: false
        default: "rockpi-4b"
      set_desktop:
        description: "Build Desktop: no / gnome / xfce, etc."
        required: false
        default: "no"
      armbian_kernel:
        description: "Set kernel version."
        required: false
        default: "5.15.25_5.10.100"
      armbian_size:
        description: "Set armbian rootfs size."
        required: false
        default: "2748"
      armbian_fstype:
        description: "Set armbian rootfs type."
        required: false
        default: "ext4"
      armbian_sign:
        description: "Set armbian custom name."
        required: false
        default: ""

env:
  BUILD_MINIMAL: yes
  KERNEL_CONFIGURE: no
  BUILD_DESKTOP: no
  HOST: aros

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean

        set_board="${{ github.event.inputs.set_board }}"
        if [[ -z "${set_board}" ]]; then
          set_board="rockpi-4b"
        fi
        echo "BOARD=${set_board}" >> $GITHUB_ENV

        set_branch="${{ github.event.inputs.set_branch }}"
        if [[ -z "${set_branch}" ]]; then
          set_branch="current"
        fi
        echo "BRANCH=${set_branch}" >> $GITHUB_ENV

        set_release="${{ github.event.inputs.set_release }}"
        if [[ -z "${set_release}" ]]; then
          set_release="focal"
        fi
        echo "RELEASE=${set_release}" >> $GITHUB_ENV

    - name: Download source code
      run: |
        git clone --depth 1 https://github.com/armbian/build.git

    - name: Patch source with customizations
      run: |
        mkdir -p build/output/
        mkdir -p build/userpatches/
        mkdir -p build/userpatches/overlay
        cp -aR armbian/base/* build/userpatches/overlay/
        cp -a armbian/base/customize-image.sh build/userpatches/
        cp -a armbian/base/config-default.conf build/userpatches/

    - name: Compile Armbian
      id: build
      run: |
        cd build/
        sudo chmod +x compile.sh
        ./compile.sh BUILD_MINIMAL=$BUILD_MINIMAL BOARD=${{ env.BOARD }} BRANCH=${{ env.BRANCH }} RELEASE=${{ env.RELEASE }} BUILD_DESKTOP=$BUILD_DESKTOP HOST=$HOST default
        echo "::set-output name=status::success"
        pwd
        tar -cjvf /tmp/AROS_${BOARD}.tar.bz2 output/images/*.img

    - name: Debug Output
      if: always()
      run: |
        pwd
        ls -lR build/userpatches build/output build/config build/patch || /bin/true

    - name: Upload Armbian image
      uses: actions/upload-artifact@master
      if: steps.build.outputs.status == 'success'
      with:
        name: AROS_${BOARD}
        path: /tmp/AROS_${BOARD}.tar.bz2
